services:
  - type: web
    name: pomegranate-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: "]oz2L*|IkL5*yZ-&A*G.2cLVAYcM;5H0uWwE%d$jE!o"
      - key: MONGO_URI
        value: "mongodb+srv://abhisekpatel8917_db_user:Abhi1234@cluster0.epxf3si.mongodb.net/pomegranate_db?retryWrites=true&w=majority&appName=Cluster0"
      - key: ML_SERVICE_URL
        value: "http://localhost:8000"
